# Generated by Django 2.1.1 on 2018-09-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('currency_name', models.CharField(max_length=3)),
                ('currency_base_name', models.CharField(max_length=3)),
                ('rate', models.FloatField()),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date', 'currency_name'],
            },
        ),
    ]
