version: '3'

services:
  rabbit:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build:
      context: .
    depends_on:
      - rabbit
    links:
      - rabbit

    ports:
      - "80:80"
