version: "2"

services:

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=python_exercice
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./db:/var/lib/mysql"

  web:
    image: python_exercice_web:1.2.2
    build: ./web
    environment:
      - DJANGO_SETTINGS_MODULE=python_exercice.config.dev
      - ASSET_PATH=/s
    command: >
      bash -c "/usr/local/bin/django-admin migrate
      && /usr/local/bin/django-admin collect_last_month_rates
      && /usr/local/bin/django-admin runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - "./web:/usr/src/python_exercice"
    depends_on:
      - db
      - celery
    links:
      - db:db

  nginx:
    image: python_exercice_nginx:1.2.1
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    environment:
      - NGINX_SERVER=localhost
    command: /bin/bash -c "envsubst '$$NGINX_SERVER' < /etc/nginx/templates/dev.template.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - web
    links:
      - web:web

  celery:
    image: python_exercice_web:1.2.2
    build: ./web
    environment:
      - DJANGO_SETTINGS_MODULE=python_exercice.config.dev
      - PYTHON_EGG_CACHE=/tmp
    working_dir: /usr/src/python_exercice
    command: su -m celery_user -c "celery -A python_exercice worker --loglevel=info --beat --concurrency=1 -n worker1@%h"
    restart: always
    volumes:
      - "./web:/usr/src/python_exercice"
    depends_on:
      - db

  redis:
    image: redis:4
    ports:
      - "6379:6379"
