# Generated by Django 2.1 on 2018-08-28 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=3)),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('value', models.DecimalField(decimal_places=6, max_digits=50)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='core.Entry')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('entry', 'currency')},
        ),
    ]
